SELECT * FROM public."Customers";

ALTER TABLE public."Customers"
ADD COLUMN first_name VARCHAR(50),
ADD COLUMN last_name VARCHAR(50),
ADD COLUMN email VARCHAR(100) UNIQUE,
ADD COLUMN phone VARCHAR(20),
ADD COLUMN address VARCHAR(255),
ADD COLUMN city VARCHAR(50),
ADD COLUMN country VARCHAR(50),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
